// Generated by gencpp from file single_actuator/gravity_currentRequest.msg
// DO NOT EDIT!


#ifndef SINGLE_ACTUATOR_MESSAGE_GRAVITY_CURRENTREQUEST_H
#define SINGLE_ACTUATOR_MESSAGE_GRAVITY_CURRENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace single_actuator
{
template <class ContainerAllocator>
struct gravity_currentRequest_
{
  typedef gravity_currentRequest_<ContainerAllocator> Type;

  gravity_currentRequest_()
    {
    }
  gravity_currentRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::single_actuator::gravity_currentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::single_actuator::gravity_currentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gravity_currentRequest_

typedef ::single_actuator::gravity_currentRequest_<std::allocator<void> > gravity_currentRequest;

typedef boost::shared_ptr< ::single_actuator::gravity_currentRequest > gravity_currentRequestPtr;
typedef boost::shared_ptr< ::single_actuator::gravity_currentRequest const> gravity_currentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::single_actuator::gravity_currentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace single_actuator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::single_actuator::gravity_currentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::single_actuator::gravity_currentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::single_actuator::gravity_currentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::single_actuator::gravity_currentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "single_actuator/gravity_currentRequest";
  }

  static const char* value(const ::single_actuator::gravity_currentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::single_actuator::gravity_currentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gravity_currentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::single_actuator::gravity_currentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::single_actuator::gravity_currentRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SINGLE_ACTUATOR_MESSAGE_GRAVITY_CURRENTREQUEST_H
