# Feature Selection
feature: torque_identification  # speed_riction_detection, torque_friction_detection, torque_identification

# Path to record data
record_path: "record_data"

# Actuator control cycle
control_cycle: 0.0025

test_velocity: 0.02

# Calculate the current value output by the actuator when the actuator angle is 90 degrees 
# (the arm is parallel to the horizontal plane)
service_topic: max_current_overcomes_gravity

# Serial port number
DEVICE_NAME: /dev/ttyUSB0

# Serial baud rate
BAUDRATE: 921600

link:
  Actuator_ID: 0

  # Actuator reduction ratio
  Reduction: 101

  # Actuator hardware limitations
  jnt_limit:
    lower: -4
    upper: 4
    tor: 26.89195
    vel: 1.57
  
  # Maximum current (mA)
  max_current: 10000

  # Conversion factor from current to torque
  cur_tor_fastor: 0.002735

  # Parameters of the polynomial fitting the friction current, the size is 7*joints_number
  Frict_param: [158.30740053,  -928.30079747,  1858.18713739, -1387.20501424,
                -119.56101981,  1009.81363785,   277.74169198]
  # Friction parameter in the power-assist direction, the size is 2
  # (used to adjust the friction change caused by the torque change when the rotation 
  # direction is the same as the current torque direction)
  # The third element is used to control the ratio. If you feel resistance, increase this parameter, otherwise decrease it.
  frict_param_assist: [4.255464274031258, 9.719952955145573, 1.1]
  # Resistance direction friction parameter, the size is 2
  # (used to adjust the friction change caused by torque change when the rotation
  # direction is opposite to the current torque direction)
  # The third element is used to control the ratio. If you feel resistance, increase this parameter, otherwise decrease it.
  frict_param_resistance: [2.133012878353566, 34.259293124848604, 1.3]